require.config({
	'baseUrl':'/media/js',
	'paths':{
		'knockout':'vendor/knockout',
		'jquery':'//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min',
		'autogrow':'vendor/jquery.autosize',
		'validate':'vendor/jquery.validate.min',
		'jgrowl':'vendor/jgrowl.min',
		'markdown':'vendor/markdown',
		'd3':'//cdnjs.cloudflare.com/ajax/libs/d3/3.5.2/d3.min.js',
		'charts':'vendor/chart'
	},
	'shim':{
		'autogrow':{
			'deps':['jquery']
		},
		'validate':{
			'deps':['jquery']
		},
		'jgrowl':{
			'deps':['jquery']
		},
		'chartjs':{
			'deps':['jquery']
		},
		'markdown':{
			exports:'markdown'
		}
	}
});